"""Custom functions called in-process from custom_functions.feature.

Any function here (or in any module) can be a Gherkin step:
    When User calls the function "path/to/helpers.py:add" with args "2 3" and saves the result as `SUM`
Args arrive as strings (shlex-split); the return value lands in `FUNCTION_RESULT`
and the named var. This is where JDBC-style setup code would live in Java land —
connect to a database, seed a schema, mint a token — anything Python can do.
"""
import uuid


def add(a, b):
    return int(a) + int(b)


def make_username(prefix="noodle"):
    """Generate a unique username — demonstrates a value produced by one step
    and consumed by later steps (dependency injection via `VAR`)."""
    return f"{prefix}-{uuid.uuid4().hex[:6]}"


def greet(username):
    """Consumes a value generated by an earlier step."""
    return f"Hello, {username}!"
